### PR TITLE
Replaced deprecated gulp-util

### LINKED ISSUE #15: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by zbennett10**
This pr replaces the recently deprecated gulp-util package with corresponding dependencies and fixes #15 

For more info see:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
gulpjs/gulp-util#143

Thanks!

### CODE REVIEW

**Comment by avdeev** [comment]
@morou Review, plz

**Comment by rejas** [comment]
If @morou doesnt want to maintain this library I'd be willing to take over maintainership if that is of any help.

**Comment by morou** [comment]
first, i'm sorry for may late reply. i'll merge this PR right now.

@rejas I appreciate your offer! can I transfer ownership of this repository to you?

**Comment by rejas** [comment]
@morou yes you can. probably also on npm so I can do a release too

**Comment by morou** [comment]
@rejas It would be helpful if you release!

I'll transfer ownership now, please confirm it.

**Comment by rejas** [comment]
@morou thx, could you also transfer it on npm to me? https://www.npmjs.com/~rejas 
that way I can also release it into the npm jungle :-)

**Comment by avdeev** [comment]
Good news for this package :)

**Pull request merged**
